{
 "title": "Docker Overview - Zabbix Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "CPU_per_second",
    "query": {}
   },
   {
    "name": "usermode_usage_per_second",
    "query": {}
   },
   {
    "name": "Memory_usage",
    "query": {}
   },
   {
    "name": "Memory_maximum_usage",
    "query": {}
   },
   {
    "name": "CPU_kernelmode_usage_per_second",
    "query": {}
   },
   {
    "name": "container_bytes_sent_per_second",
    "query": {}
   },
   {
    "name": "container_bytes_received_per_second",
    "query": {}
   },
   {
    "name": "container_errors_received_per_second",
    "query": {}
   },
   {
    "name": "container_errors_sent_per_second",
    "query": {}
   },
   {
    "name": "container_incoming_packets_dropped_per_second",
    "query": {}
   },
   {
    "name": "container_outgoing_packets_dropped_per_second",
    "query": {}
   },
   {
    "name": "container_Throttled_time",
    "query": {}
   },
   {
    "name": "container_Online_CPUs",
    "query": {}
   },
   {
    "name": "container_Paused",
    "query": {}
   },
   {
    "name": "container_dead",
    "query": {}
   },
   {
    "name": "container_Throttled_periods",
    "query": {}
   },
   {
    "name": "container_running",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Docker Available Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Docker" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Images available" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Docker Container Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Docker" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Containers total" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Docker Containers Stopped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Docker" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Containers stopped" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Docker Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Docker" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Containers running" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Docker Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Docker: Volumes size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Docker: Volumes size" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$CPU_per_second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$CPU_per_second" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$CPU_per_second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$CPU_per_second" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$CPU_kernelmode_usage_per_second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$CPU_kernelmode_usage_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_Throttled_time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_Throttled_time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_Throttled_time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_Online_CPUs" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$CPU_kernelmode_usage_per_second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$CPU_kernelmode_usage_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_Throttled_periods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_Throttled_periods" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_running" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_Paused Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_Paused" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container_dead Number of Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$container_dead" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Memory_usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Memory_usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Memory_maximum_usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "$Memory_maximum_usage" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_bytes_received_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_bytes_sent_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container Network Errors ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_errors_received_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_errors_sent_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$container Network Errors ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_incoming_packets_dropped_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$container" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "$container_outgoing_packets_dropped_per_second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}